import { ENumberDatabase } from './e-number-database';

// Fortsättning på veganska E-nummer (del 4)
export const VEGAN_ENUMBERS_4: ENumberDatabase = {
  'E900': { name: 'Dimetylpolysiloxan', description: 'Syntetiskt skumdämpningsmedel', status: 'vegan' },
  'E901': { name: 'Bivax (vitt och gult)', description: 'Naturligt vax från växtbaserade källor', status: 'vegan' },
  'E902': { name: 'Kandeljävax', description: 'Vegetabiliskt ytbehandlingsmedel', status: 'vegan' },
  'E903': { name: 'Karnaubavax', description: 'Naturligt vax från palmblad', status: 'vegan' },
  'E904': { name: 'Shellack', description: 'Naturligt ytbehandlingsmedel från växter', status: 'vegan' },
  'E905': { name: 'Paraffinolja', description: 'Mineralbaserat ytbehandlingsmedel', status: 'vegan' },
  'E905a': { name: 'Paraffinolja (mikrokristallint vax)', description: 'Mineralbaserat ytbehandlingsmedel', status: 'vegan' },
  'E905b': { name: 'Paraffinolja (flytande)', description: 'Mineralbaserat ytbehandlingsmedel', status: 'vegan' },
  'E905c': { name: 'Paraffinolja (högvisköst)', description: 'Mineralbaserat ytbehandlingsmedel', status: 'vegan' },
  'E906': { name: 'Bensoeharts', description: 'Naturligt ytbehandlingsmedel från växter', status: 'vegan' },
  'E907': { name: 'Mikrokristallint vax', description: 'Mineralbaserat ytbehandlingsmedel', status: 'vegan' },
  'E908': { name: 'Risfröolja vax', description: 'Vegetabiliskt vax', status: 'vegan' },
  'E912': { name: 'Spermacetvax', description: 'Naturligt vax från växtbaserade källor', status: 'vegan' },
  'E914': { name: 'Lanolin', description: 'Växtbaserat ytbehandlingsmedel', status: 'vegan' },
  'E915': { name: 'Estrar av kolofonium', description: 'Växtbaserat ytbehandlingsmedel', status: 'vegan' },
  'E922': { name: 'Kalciumjodad', description: 'Mineralbaserat näringstillskott', status: 'vegan' },
  'E923': { name: 'Kaliumbromat', description: 'Syntetiskt mjölbehandlingsmedel', status: 'vegan' },
  'E924': { name: 'Kaliumklorit', description: 'Syntetiskt mjölbehandlingsmedel', status: 'vegan' },
  'E925': { name: 'Klor', description: 'Syntetiskt mjölbehandlingsmedel', status: 'vegan' },
  'E926': { name: 'Klorindioxid', description: 'Syntetiskt mjölbehandlingsmedel', status: 'vegan' },
  'E927b': { name: 'Azodikarbonamid', description: 'Syntetiskt mjölbehandlingsmedel', status: 'vegan' },
  'E928': { name: 'Karbamidperoxid', description: 'Syntetiskt mjölbehandlingsmedel', status: 'vegan' },
  'E930': { name: 'Kalciumperoxid', description: 'Syntetiskt mjölbehandlingsmedel', status: 'vegan' },
  'E938': { name: 'Argon', description: 'Inert förpackningsgas', status: 'vegan' },
  'E939': { name: 'Helium', description: 'Inert förpackningsgas', status: 'vegan' },
  'E940': { name: 'Dikväveoxid', description: 'Förpackningsgas', status: 'vegan' },
  'E941': { name: 'Kväve', description: 'Förpackningsgas', status: 'vegan' },
  'E942': { name: 'Dikväveoxid', description: 'Förpackningsgas', status: 'vegan' },
  'E943a': { name: 'Butan', description: 'Drivgas', status: 'vegan' },
  'E943b': { name: 'Isobutan', description: 'Drivgas', status: 'vegan' },
  'E944': { name: 'Propan', description: 'Drivgas', status: 'vegan' },
  'E948': { name: 'Syre', description: 'Förpackningsgas', status: 'vegan' },
  'E949': { name: 'Väte', description: 'Förpackningsgas', status: 'vegan' },
  'E950': { name: 'Acesulfam K', description: 'Syntetiskt sötningsmedel', status: 'vegan' },
  'E951': { name: 'Aspartam', description: 'Syntetiskt sötningsmedel', status: 'vegan' },
  'E952': { name: 'Cyklaminsyra', description: 'Syntetiskt sötningsmedel', status: 'vegan' },
  'E953': { name: 'Isomalt', description: 'Sötningsmedel från sockerbetor', status: 'vegan' },
  'E954': { name: 'Sackarin', description: 'Syntetiskt sötningsmedel', status: 'vegan' },
  'E955': { name: 'Sukralos', description: 'Syntetiskt sötningsmedel', status: 'vegan' },
  'E957': { name: 'Alitam', description: 'Syntetiskt sötningsmedel', status: 'vegan' },
  'E958': { name: 'Glycyrrhizin', description: 'Naturligt sötningsmedel från lakritsrot', status: 'vegan' },
  'E959': { name: 'Neohesperidindihydrochalkon', description: 'Syntetiskt sötningsmedel från citrusfrukter', status: 'vegan' },
  'E965': { name: 'Maltitol', description: 'Sötningsmedel från stärkelse', status: 'vegan' },
  'E967': { name: 'Xylitol', description: 'Sötningsmedel från björkved', status: 'vegan' },
  'E999': { name: 'Quillaja-extrakt', description: 'Naturligt skumbildande medel från såpbarkträd', status: 'vegan' },
  'E1400': { name: 'Glycerol', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1401': { name: 'Stärkelse oxiderad', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1402': { name: 'Stärkelse alkalisk', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1403': { name: 'Blekt stärkelse', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1404': { name: 'Oxiderad stärkelse', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1410': { name: 'Monostärkelsefosfat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1412': { name: 'Distärkelsefosfat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1413': { name: 'Fosfaterad distärkelsefosfat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1414': { name: 'Acetylerad distärkelsefosfat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1420': { name: 'Acetylerad stärkelse', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1422': { name: 'Acetylerad distärkelseadipat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1440': { name: 'Hydroxipropylstärkelse', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1442': { name: 'Hydroxipropyldistärkelsefosfat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1450': { name: 'Stärkelsenatriumoktenylsuccinat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1451': { name: 'Acetylerad oxiderad stärkelse', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1452': { name: 'Stärkelseoktenylsuccinat', description: 'Modifierad stärkelse från växter', status: 'vegan' },
  'E1505': { name: 'Cellulosa', description: 'Modifierad cellulosa från växter', status: 'vegan' },
  'E1510': { name: 'Trietylcitrat', description: 'Växtbaserad emulgator', status: 'vegan' },
  'E1520': { name: 'Propylenglykol', description: 'Syntetisk fuktighetsbevarande medel', status: 'vegan' },
}; 