import { ENumberDatabase } from './e-number-database';

// Fortsättning på veganska E-nummer (del 3)
export const VEGAN_ENUMBERS_3: ENumberDatabase = {
  'E463': { name: 'Hydroxipropylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
  'E464': { name: 'Hydroxipropylmetylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
  'E465': { name: 'Etylmetylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
  'E466': { name: 'Karboximetylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
  'E468': { name: 'Tvärbunden natriumkarboximetylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
  'E469': { name: 'Enzymatiskt hydrolyserad karboximetylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
  'E500': { name: 'Natriumkarbonat', description: 'Mineralbaserat bakpulver och surhetsreglerande medel', status: 'vegan' },
  'E501': { name: 'Kaliumkarbonat', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E503': { name: 'Ammoniumkarbonat', description: 'Mineralbaserat bakpulver', status: 'vegan' },
  'E504': { name: 'Magnesiumkarbonat', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E507': { name: 'Saltsyra', description: 'Mineralbaserad syra för pH-reglering', status: 'vegan' },
  'E508': { name: 'Kaliumklorid', description: 'Mineralbaserat salt för smakförstärkning', status: 'vegan' },
  'E509': { name: 'Kalciumklorid', description: 'Mineralbaserat salt för konsistensgivning', status: 'vegan' },
  'E510': { name: 'Ammoniumklorid', description: 'Mineralbaserat salt för pH-reglering', status: 'vegan' },
  'E511': { name: 'Magnesiumklorid', description: 'Mineralbaserat salt för konsistensgivning', status: 'vegan' },
  'E512': { name: 'Tennklorid', description: 'Mineralbaserat antioxidationsmedel', status: 'vegan' },
  'E513': { name: 'Svavelsyra', description: 'Mineralbaserad syra för pH-reglering', status: 'vegan' },
  'E514': { name: 'Natriumsulfat', description: 'Mineralbaserat salt för konsistensgivning', status: 'vegan' },
  'E515': { name: 'Kaliumsulfat', description: 'Mineralbaserat salt för konsistensgivning', status: 'vegan' },
  'E516': { name: 'Kalciumsulfat', description: 'Mineralbaserat salt för konsistensgivning', status: 'vegan' },
  'E517': { name: 'Ammoniumsulfat', description: 'Mineralbaserat salt för pH-reglering', status: 'vegan' },
  'E518': { name: 'Magnesiumsulfat', description: 'Mineralbaserat salt för konsistensgivning', status: 'vegan' },
  'E519': { name: 'Kopparsulfat', description: 'Mineralbaserat salt för näringsförstärkning', status: 'vegan' },
  'E520': { name: 'Aluminiumsulfat', description: 'Mineralbaserat stabiliseringsmedel', status: 'vegan' },
  'E521': { name: 'Aluminiumnatriumsulfat', description: 'Mineralbaserat stabiliseringsmedel', status: 'vegan' },
  'E522': { name: 'Aluminiumkaliumsulfat', description: 'Mineralbaserat stabiliseringsmedel', status: 'vegan' },
  'E523': { name: 'Aluminiumammoniumsulfat', description: 'Mineralbaserat stabiliseringsmedel', status: 'vegan' },
  'E524': { name: 'Natriumhydroxid', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E525': { name: 'Kaliumhydroxid', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E526': { name: 'Kalciumhydroxid', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E527': { name: 'Ammoniumhydroxid', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E528': { name: 'Magnesiumhydroxid', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E529': { name: 'Kalciumoxid', description: 'Mineralbaserat surhetsreglerande medel', status: 'vegan' },
  'E530': { name: 'Magnesiumoxid', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E535': { name: 'Järncyanid', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E536': { name: 'Kaliumferrocyanid', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E539': { name: 'Natriumtiosulfat', description: 'Mineralbaserat antioxidationsmedel', status: 'vegan' },
  'E540': { name: 'Dikalciumdifosfat', description: 'Mineralbaserat bakpulver', status: 'vegan' },
  'E541': { name: 'Natriumaluminiumfosfat', description: 'Mineralbaserat bakpulver', status: 'vegan' },
  'E543': { name: 'Kalciumfosfat', description: 'Mineralbaserat bakpulver', status: 'vegan' },
  'E544': { name: 'Kalciumpolyfostfat', description: 'Mineralbaserat emulgeringsmedel', status: 'vegan' },
  'E545': { name: 'Ammoniumpolyfostfat', description: 'Mineralbaserat emulgeringsmedel', status: 'vegan' },
  'E550': { name: 'Natriumsilikat', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E551': { name: 'Kiseldioxid', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E553a': { name: 'Magnesiumsilikat', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E553b': { name: 'Talk', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E554': { name: 'Natriumaluminiumsilikat', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E555': { name: 'Kaliumaluminiumsilikat', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E556': { name: 'Kalciumaluminiumsilikat', description: 'Mineralbaserat klumpförebyggande medel', status: 'vegan' },
  'E558': { name: 'Zinkoxid', description: 'Mineralbaserat färgämne', status: 'vegan' },
  'E574': { name: 'Magnesiumtartrat', description: 'Salt av vinsyra från växtriket', status: 'vegan' },
  'E575': { name: 'Glukonsyrans deltalakton', description: 'Naturligt förekommande syra', status: 'vegan' },
  'E576': { name: 'Natriumglukonat', description: 'Salt av glukonsyra från växtriket', status: 'vegan' },
  'E577': { name: 'Kaliumglukonat', description: 'Salt av glukonsyra från växtriket', status: 'vegan' },
  'E578': { name: 'Kalciumglukonat', description: 'Salt av glukonsyra från växtriket', status: 'vegan' },
  'E579': { name: 'Järnglukonat', description: 'Salt av glukonsyra med järn', status: 'vegan' },
  'E620': { name: 'Glutaminsyra', description: 'Naturlig smakförstärkare från växtproteiner', status: 'vegan' },
  'E621': { name: 'Mononatriumglutamat', description: 'Salt av glutaminsyra för smakförstärkning', status: 'vegan' },
  'E622': { name: 'Monokaliumglutamat', description: 'Salt av glutaminsyra för smakförstärkning', status: 'vegan' },
  'E623': { name: 'Kalciumdiglutamat', description: 'Salt av glutaminsyra för smakförstärkning', status: 'vegan' },
  'E624': { name: 'Monoammoniumglutamat', description: 'Salt av glutaminsyra för smakförstärkning', status: 'vegan' },
  'E625': { name: 'Magnesiumdiglutamat', description: 'Salt av glutaminsyra för smakförstärkning', status: 'vegan' },
}; 