import { ENumberDatabase } from './e-number-database';

// Fortsättning på veganska E-nummer (del 2)
export const VEGAN_ENUMBERS_2: ENumberDatabase = {
  'E181': { name: 'Tannin', description: 'Naturligt färgämne från växter', status: 'vegan' },
  'E200': { name: 'Sorbinsyra', description: 'Naturligt konserveringsmedel från rönnbär', status: 'vegan' },
  'E201': { name: 'Natriumsorbat', description: 'Salt av sorbinsyra för konservering', status: 'vegan' },
  'E202': { name: 'Kaliumsorbat', description: 'Salt av sorbinsyra för konservering', status: 'vegan' },
  'E203': { name: 'Kalciumsorbat', description: 'Salt av sorbinsyra för konservering', status: 'vegan' },
  'E210': { name: 'Bensoesyra', description: 'Naturligt förekommande konserveringsmedel från bär', status: 'vegan' },
  'E211': { name: 'Natriumbensoat', description: 'Salt av bensoesyra för konservering', status: 'vegan' },
  'E212': { name: 'Kaliumbensoat', description: 'Salt av bensoesyra för konservering', status: 'vegan' },
  'E213': { name: 'Kalciumbensoat', description: 'Salt av bensoesyra för konservering', status: 'vegan' },
  'E214': { name: 'Para-hydroxybensoesyraetylester', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E215': { name: 'Para-hydroxybensoesyranatriumetylester', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E216': { name: 'Para-hydroxybensoesyrapropylester', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E218': { name: 'Para-hydroxybensoesyrametylester', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E219': { name: 'Para-hydroxybensoesyranatriumpropylester', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E220': { name: 'Svaveldioxid', description: 'Konserveringsmedel och antioxidationsmedel', status: 'vegan' },
  'E221': { name: 'Natriumsulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E222': { name: 'Natriumvätesulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E223': { name: 'Natriummetabisulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E224': { name: 'Kaliummetabisulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E225': { name: 'Kaliumsulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E226': { name: 'Kalciumsulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E227': { name: 'Kalciumvätesulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E228': { name: 'Kaliumbisulfit', description: 'Sulfitbaserat konserveringsmedel', status: 'vegan' },
  'E230': { name: 'Bifenyl', description: 'Syntetiskt konserveringsmedel för citrusfrukter', status: 'vegan' },
  'E231': { name: 'Ortofenylfenol', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E232': { name: 'Natriumortofenylfenol', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E233': { name: 'Tiabendazol', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E234': { name: 'Nisin', description: 'Naturligt antimikrobiellt ämne', status: 'vegan' },
  'E235': { name: 'Natamycin', description: 'Naturligt antimikrobiellt ämne', status: 'vegan' },
  'E236': { name: 'Myrsyra', description: 'Naturligt förekommande konserveringsmedel', status: 'vegan' },
  'E237': { name: 'Natriumformiat', description: 'Salt av myrsyra för konservering', status: 'vegan' },
  'E238': { name: 'Kalciumformiat', description: 'Salt av myrsyra för konservering', status: 'vegan' },
  'E239': { name: 'Hexametylentetramin', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E240': { name: 'Formaldehyd', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E242': { name: 'Dimetyldikarbonat', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E249': { name: 'Kaliumnitrit', description: 'Konserveringsmedel för vegetabiliska produkter', status: 'vegan' },
  'E250': { name: 'Natriumnitrit', description: 'Konserveringsmedel för vegetabiliska produkter', status: 'vegan' },
  'E251': { name: 'Natriumnitrat', description: 'Konserveringsmedel för vegetabiliska produkter', status: 'vegan' },
  'E260': { name: 'Ättiksyra', description: 'Naturlig syra från fermentering', status: 'vegan' },
  'E261': { name: 'Kaliumacetat', description: 'Salt av ättiksyra', status: 'vegan' },
  'E262': { name: 'Natriumacetat', description: 'Salt av ättiksyra', status: 'vegan' },
  'E263': { name: 'Kalciumacetat', description: 'Salt av ättiksyra', status: 'vegan' },
  'E264': { name: 'Ammoniumacetat', description: 'Salt av ättiksyra', status: 'vegan' },
  'E270': { name: 'Mjölksyra', description: 'Naturlig syra från växtfermentering', status: 'vegan' },
  'E280': { name: 'Propionsyra', description: 'Naturligt förekommande konserveringsmedel', status: 'vegan' },
  'E281': { name: 'Natriumpropionat', description: 'Salt av propionsyra', status: 'vegan' },
  'E282': { name: 'Kalciumpropionat', description: 'Salt av propionsyra', status: 'vegan' },
  'E283': { name: 'Kaliumpropionat', description: 'Salt av propionsyra', status: 'vegan' },
  'E284': { name: 'Borsyra', description: 'Naturligt konserveringsmedel', status: 'vegan' },
  'E285': { name: 'Natriumtetraborat', description: 'Mineralbaserat konserveringsmedel', status: 'vegan' },
  'E290': { name: 'Koldioxid', description: 'Naturligt förekommande gas för konservering', status: 'vegan' },
  'E296': { name: 'Äppelsyra', description: 'Naturlig syra från äpplen', status: 'vegan' },
  'E297': { name: 'L-askorbinsyra', description: 'Syntetisk variant av vitamin C', status: 'vegan' },
  'E300': { name: 'Askorbinsyra', description: 'Naturligt antioxidationsmedel (vitamin C)', status: 'vegan' },
  'E301': { name: 'Natriumaskorbat', description: 'Salt av askorbinsyra (vitamin C)', status: 'vegan' },
  'E302': { name: 'Kalciumaskorbat', description: 'Salt av askorbinsyra (vitamin C)', status: 'vegan' },
  'E303': { name: 'Kaliumaskorbat', description: 'Salt av askorbinsyra (vitamin C)', status: 'vegan' },
  'E306': { name: 'Tokoferolkoncentrat', description: 'Naturligt vitamin E från växter', status: 'vegan' },
  'E307': { name: 'Syntetiskt alfa-tokoferol', description: 'Syntetisk form av vitamin E', status: 'vegan' },
  'E308': { name: 'Syntetiskt gamma-tokoferol', description: 'Syntetisk form av vitamin E', status: 'vegan' },
  'E309': { name: 'Syntetiskt delta-tokoferol', description: 'Syntetisk form av vitamin E', status: 'vegan' },
  'E310': { name: 'Propylgallat', description: 'Syntetiskt antioxidationsmedel', status: 'vegan' },
  'E311': { name: 'Oktylgallat', description: 'Syntetiskt antioxidationsmedel', status: 'vegan' },
  'E312': { name: 'Dodecylgallat', description: 'Syntetiskt antioxidationsmedel', status: 'vegan' },
  'E315': { name: 'Erytorbinsyra', description: 'Syntetiskt antioxidationsmedel', status: 'vegan' },
  'E316': { name: 'Natriumerytorbat', description: 'Salt av erytorbinsyra', status: 'vegan' },
  'E317': { name: 'Kalciumerytorbat', description: 'Salt av erytorbinsyra', status: 'vegan' },
  'E318': { name: 'Kaliumerytorbat', description: 'Salt av erytorbinsyra', status: 'vegan' },
  'E320': { name: 'Butylhydroxianisol (BHA)', description: 'Syntetiskt antioxidationsmedel', status: 'vegan' },
  'E321': { name: 'Butylhydroxitoluen (BHT)', description: 'Syntetiskt antioxidationsmedel', status: 'vegan' },
  'E325': { name: 'Natriumlaktat', description: 'Salt av mjölksyra från växtfermentering', status: 'vegan' },
  'E326': { name: 'Kaliumlaktat', description: 'Salt av mjölksyra från växtfermentering', status: 'vegan' },
  'E327': { name: 'Kalciumlaktat', description: 'Salt av mjölksyra från växtfermentering', status: 'vegan' },
  'E330': { name: 'Citronsyra', description: 'Naturlig syra från citrusfrukter', status: 'vegan' },
  'E331': { name: 'Natriumcitrat', description: 'Salt av citronsyra', status: 'vegan' },
  'E332': { name: 'Kaliumcitrat', description: 'Salt av citronsyra', status: 'vegan' },
  'E333': { name: 'Kalciumcitrat', description: 'Salt av citronsyra', status: 'vegan' },
  'E334': { name: 'Vinsyra', description: 'Naturlig syra från vindruvor', status: 'vegan' },
  'E335': { name: 'Natriumtartrat', description: 'Salt av vinsyra', status: 'vegan' },
  'E336': { name: 'Kaliumtartrat', description: 'Salt av vinsyra', status: 'vegan' },
  'E337': { name: 'Kaliumnatriumtartrat', description: 'Dubbelsalt av vinsyra', status: 'vegan' },
  'E338': { name: 'Fosforsyra', description: 'Mineralbaserad syra', status: 'vegan' },
  'E339': { name: 'Natriumfosfat', description: 'Salt av fosforsyra', status: 'vegan' },
  'E340': { name: 'Kaliumfosfat', description: 'Salt av fosforsyra', status: 'vegan' },
  'E341': { name: 'Kalciumfosfat', description: 'Salt av fosforsyra', status: 'vegan' },
  'E343': { name: 'Magnesiumfosfat', description: 'Salt av fosforsyra', status: 'vegan' },
  'E350': { name: 'Natriummalat', description: 'Salt av äppelsyra', status: 'vegan' },
  'E351': { name: 'Kaliummalat', description: 'Salt av äppelsyra', status: 'vegan' },
  'E352': { name: 'Kalciummalat', description: 'Salt av äppelsyra', status: 'vegan' },
  'E353': { name: 'Metavinsyra', description: 'Modifierad form av vinsyra', status: 'vegan' },
  'E354': { name: 'Kalciumtartrat', description: 'Salt av vinsyra', status: 'vegan' },
  'E355': { name: 'Adipinsyra', description: 'Syntetisk syra', status: 'vegan' },
  'E356': { name: 'Natriumadipat', description: 'Salt av adipinsyra', status: 'vegan' },
  'E357': { name: 'Kaliumadipat', description: 'Salt av adipinsyra', status: 'vegan' },
  'E363': { name: 'Bärnstenssyra', description: 'Naturligt förekommande syra', status: 'vegan' },
  'E365': { name: 'Fumarsyra', description: 'Naturligt förekommande syra', status: 'vegan' },
  'E366': { name: 'Kaliumfumarat', description: 'Salt av fumarsyra', status: 'vegan' },
  'E367': { name: 'Kalciumfumarat', description: 'Salt av fumarsyra', status: 'vegan' },
  'E375': { name: 'Nikotinsyra', description: 'Vitamin B3', status: 'vegan' },
  'E380': { name: 'Kalciumglukonat', description: 'Salt av glukonsyra från växter', status: 'vegan' },
  'E381': { name: 'Järnammoniumcitrat', description: 'Järnförening av citronsyra', status: 'vegan' },
  'E385': { name: 'Kalciumdinatrium-EDTA', description: 'Syntetiskt konserveringsmedel', status: 'vegan' },
  'E400': { name: 'Alginsyra', description: 'Naturligt förtjockningsmedel från brunalger', status: 'vegan' },
  'E401': { name: 'Natriumalginat', description: 'Salt av alginsyra från brunalger', status: 'vegan' },
  'E402': { name: 'Kaliumalginat', description: 'Salt av alginsyra från brunalger', status: 'vegan' },
  'E403': { name: 'Ammoniumalginat', description: 'Salt av alginsyra från brunalger', status: 'vegan' },
  'E404': { name: 'Kalciumalginat', description: 'Salt av alginsyra från brunalger', status: 'vegan' },
  'E405': { name: 'Propylenglykolalginat', description: 'Modifierad alginat från brunalger', status: 'vegan' },
  'E406': { name: 'Agar', description: 'Naturligt förtjockningsmedel från rödalger', status: 'vegan' },
  'E407': { name: 'Karragenan', description: 'Naturligt förtjockningsmedel från rödalger', status: 'vegan' },
  'E410': { name: 'Fruktkärnmjöl', description: 'Naturligt förtjockningsmedel från johannesbröd', status: 'vegan' },
  'E412': { name: 'Guarkärnmjöl', description: 'Naturligt förtjockningsmedel från guarböna', status: 'vegan' },
  'E413': { name: 'Dragant', description: 'Naturligt förtjockningsmedel från dragantbuske', status: 'vegan' },
  'E414': { name: 'Arabiskt gummi', description: 'Naturligt förtjockningsmedel från akaciaträd', status: 'vegan' },
  'E415': { name: 'Xantangummi', description: 'Naturligt förtjockningsmedel från bakteriefermentering', status: 'vegan' },
  'E416': { name: 'Karayagummi', description: 'Naturligt förtjockningsmedel från karayaträd', status: 'vegan' },
  'E417': { name: 'Taragummi', description: 'Naturligt förtjockningsmedel från taragummibuske', status: 'vegan' },
  'E418': { name: 'Gellangummi', description: 'Naturligt förtjockningsmedel från bakteriefermentering', status: 'vegan' },
  'E420': { name: 'Sorbitol', description: 'Sötningsmedel från växtbaserade källor', status: 'vegan' },
  'E421': { name: 'Mannitol', description: 'Sötningsmedel från växtbaserade källor', status: 'vegan' },
  'E425': { name: 'Konjak', description: 'Naturligt förtjockningsmedel från konjakrot', status: 'vegan' },
  'E440': { name: 'Pektin', description: 'Naturligt förtjockningsmedel från frukt', status: 'vegan' },
  'E444': { name: 'Kaliumfosfatider', description: 'Emulgeringsmedel från växtbaserade källor', status: 'vegan' },
  'E450': { name: 'Difosfater', description: 'Syntetiska stabiliseringsmedel', status: 'vegan' },
  'E451': { name: 'Trifosfater', description: 'Syntetiska stabiliseringsmedel', status: 'vegan' },
  'E452': { name: 'Polyfosfater', description: 'Syntetiska stabiliseringsmedel', status: 'vegan' },
  'E459': { name: 'Beta-cyklodextrin', description: 'Stabiliseringsmedel från stärkelse', status: 'vegan' },
  'E460': { name: 'Cellulosapulver', description: 'Naturligt förtjockningsmedel från växtfibrer', status: 'vegan' },
  'E461': { name: 'Metylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
  'E462': { name: 'Etylcellulosa', description: 'Modifierad cellulosa från växtfibrer', status: 'vegan' },
}; 