// Define our E-number types
export type ENumberStatus = 'vegan' | 'non-vegan' | 'uncertain';

export interface ENumberInfo {
  name: string;
  description: string;
  status: ENumberStatus;
}

export interface ENumberDatabase {
  [key: string]: ENumberInfo;
}

// Non-vegan E-numbers database från backend
export const NON_VEGAN_ENUMBERS: ENumberDatabase = {
  'E120': { name: 'Karmin', description: 'Rött färgämne utvinnet från koschenillsköldlöss (Dactylopius coccus). Används ofta i röda livsmedel och kosmetika', status: 'non-vegan' },
  'E441': { name: 'Gelatin', description: 'Protein utvunnet från djurvävnad (hud ben och bindväv). Används ej längre som E-nummer men förekommer som ingrediens', status: 'non-vegan' },
  'E901': { name: 'Bivax', description: 'Naturligt vax producerat av honungsbin. Används som ytbehandlingsmedel och glansmedel', status: 'non-vegan' },
  'E904': { name: 'Shellack', description: 'Naturligt hartssekret från lacksköldlusen. Används som ytbehandlingsmedel och glansmedel på frukt och godis', status: 'non-vegan' },
  'E920': { name: 'L-cystein', description: 'Aminosyra traditionellt utvunnen från djurhorn eller fjädrar. Används som mjölbehandlingsmedel', status: 'non-vegan' },
  'E966': { name: 'Laktitol', description: 'Sötningsmedel framställt genom hydrering av laktos (mjölksocker) från komjölk', status: 'non-vegan' },
  'E1105': { name: 'Lysozym', description: 'Enzym utvunnet ur äggvita. Används som konserveringsmedel särskilt i ost', status: 'non-vegan' },
};

// Uncertain E-numbers database från backend
export const UNCERTAIN_ENUMBERS: ENumberDatabase = {
  'E304': { name: 'Askorbylplamitat och askorbylstearat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E322': { name: 'Lecitin', description: 'Kan vara från ägg eller soja', status: 'uncertain' },
  'E422': { name: 'Glycerol', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E431': { name: 'Polyxietylenstearat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E432': { name: 'Polyoxietylensorbitanmonolaurat', description: 'Emulgeringsmedel som kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E433': { name: 'Polyoxietylensorbitanmonooleat', description: 'Emulgeringsmedel som kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E434': { name: 'Polyoxietylensorbitanmonopalmitat', description: 'Emulgeringsmedel som kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E435': { name: 'Polyoxietylensorbitantristearat', description: 'Emulgeringsmedel som kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E436': { name: 'Polyoxietylensorbitantristearat', description: 'Emulgeringsmedel som kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E442': { name: 'Ammoniumfosfatider', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E445': { name: 'Glycerolestrar av trähartser', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E470a': { name: 'Natruim- kalium- och kalciumsalter av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E470b': { name: 'Magnesiumsalt av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E471': { name: 'Mono- och diglyceriders av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E472a': { name: 'Mono- och diglyceriders ättiksyraestrar', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E472b': { name: 'Mono- och diglyceriders mjölksyraestrar', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E472c': { name: 'Mono- och diglyceriders citronsyraestrar', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E472d': { name: 'Mono- och diglyceriders vinsyraestrar', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E472e': { name: 'Mono- och diglyceriders Diacetylvinsyraestrar', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E472f': { name: 'Blandade ättik- och vinsyraestrar av mono- och diglycerider', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E473': { name: 'Sackarosestrar av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E474': { name: 'Sackarosestrar i blandning med mono- och diglycerider av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E475': { name: 'Polyglycerolestrar av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E476': { name: 'Polyglycerolpolyricinoleat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E477': { name: 'Propylenglykolestrar av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E479b': { name: 'Termiskt oxiderad sojaolja i reaktion med mono- och diglycerider av fettsyror', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E481': { name: 'Natriumstearyoyllaktylat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E482': { name: 'Natriumstearyoyllaktylat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E483': { name: 'Stearoyltartrat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E491': { name: 'Sorbitanmonostearat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E492': { name: 'Sorbitantristearat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E493': { name: 'Sorbitanmonolaurat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E494': { name: 'Sorbitan monooleat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E495': { name: 'Sorbitanmonopalmitat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E570': { name: 'Fettsyror', description: 'Kan vara från växt- eller djurfetter', status: 'uncertain' },
  'E626': { name: 'Guanylsyra', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E627': { name: 'Dinatriumguanylat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E628': { name: 'Dikaliumguanylat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E629': { name: 'Kalciumguanylat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E630': { name: 'Inosinsyra', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E631': { name: 'Dinatriumosinat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E632': { name: 'Dikaliuminosinat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E633': { name: 'Kalciuminosinat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E634': { name: 'Kalcium-5′-ribonukleinsyra', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E635': { name: 'Dinatrium-5′-riboneukleotider', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E636': { name: 'Maltol', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E637': { name: 'Ethyl maltol', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E1517': { name: 'Glyceryldiacetat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
  'E1518': { name: 'Glyceryltriacetat', description: 'Kan vara växt- eller djurbaserad', status: 'uncertain' },
};

// Vegan E-numbers database (huvuddel)
export const VEGAN_ENUMBERS: ENumberDatabase = {
  'E100': { name: 'Kurkumin', description: 'Färgämne från gurkmeja', status: 'vegan' },
  'E101': { name: 'Riboflavin', description: 'Vitamin B2 från växtriket', status: 'vegan' },
  'E101a': { name: 'Riboflavin-5-fosfat', description: 'Vitamin B2 derivat från växtriket', status: 'vegan' },
  'E102': { name: 'Tartrazin', description: 'Syntetiskt gult färgämne', status: 'vegan' },
  'E103': { name: 'Krysoin S', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E104': { name: 'Kinolingult', description: 'Syntetiskt gult färgämne', status: 'vegan' },
  'E105': { name: 'Fast Yellow AB', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E106': { name: 'Riboflavin-5-natriumfosfat', description: 'Vitamin B2 derivat', status: 'vegan' },
  'E107': { name: 'Yellow 2G', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E110': { name: 'Para-orange', description: 'Syntetiskt orange färgämne', status: 'vegan' },
  'E111': { name: 'Orange GGN', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E122': { name: 'Karmosin', description: 'Syntetiskt rött färgämne', status: 'vegan' },
  'E123': { name: 'Amarant', description: 'Syntetiskt rött färgämne', status: 'vegan' },
  'E124': { name: 'Nykockin', description: 'Syntetiskt rött färgämne', status: 'vegan' },
  'E125': { name: 'Scharlakan GN', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E126': { name: 'Ponceau 6R', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E127': { name: 'Erytrosin', description: 'Syntetiskt rött färgämne', status: 'vegan' },
  'E128': { name: 'Röd 2G', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E129': { name: 'Allurarött AC', description: 'Syntetiskt rött färgämne', status: 'vegan' },
  'E130': { name: 'Indantrén blått RS', description: 'Syntetiskt färgämne', status: 'vegan' },
  'E131': { name: 'Patentblått V', description: 'Syntetiskt blått färgämne', status: 'vegan' },
  'E132': { name: 'Indigotin', description: 'Syntetiskt blått färgämne', status: 'vegan' },
  'E133': { name: 'Briljantblått FCF', description: 'Syntetiskt blått färgämne', status: 'vegan' },
  'E140': { name: 'Klorofyll', description: 'Naturligt grönt färgämne från växter', status: 'vegan' },
  'E141': { name: 'Klorofyllkopplexer', description: 'Naturligt grönt färgämne från växter', status: 'vegan' },
  'E142': { name: 'Grön S', description: 'Syntetiskt grönt färgämne', status: 'vegan' },
  'E143': { name: 'Fast Green FCF', description: 'Syntetiskt grönt färgämne', status: 'vegan' },
  'E150a': { name: 'Sockerkulör (karamell)', description: 'Naturligt brunt färgämne från karamelliserat socker', status: 'vegan' },
  'E150b': { name: 'Alkalisk sulfitprocessad sockerkulör', description: 'Karamelliserat socker med alkalisk sulfitprocess', status: 'vegan' },
  'E150c': { name: 'Ammoniumprocessad sockerkulör', description: 'Karamelliserat socker med ammoniakprocess', status: 'vegan' },
  'E150d': { name: 'Ammoniaksulfitprocessad sockerkulör', description: 'Karamelliserat socker med ammoniaksulfitprocess', status: 'vegan' },
  'E151': { name: 'Briljantsvart BN', description: 'Syntetiskt svart färgämne', status: 'vegan' },
  'E152': { name: 'Svart 7984', description: 'Syntetiskt svart färgämne', status: 'vegan' },
  'E153': { name: 'Vegetabiliskt kol', description: 'Naturligt svart färgämne från växtmaterial', status: 'vegan' },
  'E154': { name: 'Brun FK', description: 'Syntetiskt brunt färgämne', status: 'vegan' },
  'E155': { name: 'Brun HT', description: 'Syntetiskt brunt färgämne', status: 'vegan' },
  'E160a': { name: 'Beta-karoten', description: 'Naturligt orange färgämne från växter', status: 'vegan' },
  'E160b': { name: 'Annatto', description: 'Naturligt orange färgämne från växten annatto', status: 'vegan' },
  'E160c': { name: 'Paprikaoleoresin', description: 'Naturligt rött färgämne från paprika', status: 'vegan' },
  'E160d': { name: 'Lykopen', description: 'Naturligt rött färgämne från tomater och andra röda växter', status: 'vegan' },
  'E160e': { name: 'Beta-apo-8-karotenal', description: 'Syntetiskt orange färgämne', status: 'vegan' },
  'E160f': { name: 'Beta-apo-8-karotensyra etylester', description: 'Syntetiskt orange färgämne', status: 'vegan' },
  'E161a': { name: 'Flavoxantin', description: 'Naturligt gult färgämne från växter', status: 'vegan' },
  'E161b': { name: 'Lutein', description: 'Naturligt gult färgämne från växter', status: 'vegan' },
  'E161c': { name: 'Kryptoxantin', description: 'Naturligt gult färgämne från växter', status: 'vegan' },
  'E161d': { name: 'Rubixantin', description: 'Naturligt gult färgämne från växter', status: 'vegan' },
  'E161e': { name: 'Violaxantin', description: 'Naturligt gult färgämne från växter', status: 'vegan' },
  'E161f': { name: 'Rodoxantin', description: 'Naturligt rött färgämne från växter', status: 'vegan' },
  'E162': { name: 'Rödbetsrött', description: 'Naturligt rött färgämne från rödbetor', status: 'vegan' },
  'E163': { name: 'Antocyaner', description: 'Naturligt rött-blått färgämne från bär och frukt', status: 'vegan' },
  'E170': { name: 'Kalciumkarbonat', description: 'Mineralbaserat vitt färgämne och surhetsreglerande medel', status: 'vegan' },
  'E171': { name: 'Titandioxid', description: 'Mineralbaserat vitt färgämne', status: 'vegan' },
  'E172': { name: 'Järnoxider och järnhydroxider', description: 'Mineralbaserade färgämnen i rött gult och svart', status: 'vegan' },
  'E173': { name: 'Aluminium', description: 'Mineralbaserat silverfärgat färgämne', status: 'vegan' },
  'E174': { name: 'Silver', description: 'Mineralbaserat silverfärgat färgämne', status: 'vegan' },
  'E175': { name: 'Guld', description: 'Mineralbaserat guldfärgat färgämne', status: 'vegan' },
  'E180': { name: 'Litolrubin BK', description: 'Syntetiskt rött färgämne', status: 'vegan' },
}; 